baseUrl: 'https://www.saucedemo.com/'
baseTableTestUrl: 'https://www.coingecko.com/'
baseUrlApi: 'https://jsonplaceholder.typicode.com'
endpoints:
  - name: 'getPosts'
    method: 'GET'
    path: '/posts'
  - name: 'getPost'
    method: 'GET'
    path: '/posts/{id}'
  - name: 'createPost'
    method: 'POST'
    path: '/posts'
